9oogling/CodyUs

src/main/java/com/team9oogling/ecommerce/global/config/SecurityConfig.java
=> [2024/07/17] feature/create-security >> security 초기 설정

.gitignore, src/main/java/com/team9oogling/ecommerce/global/config/SecurityConfig.java, src/main/java/com/team9oogling/ecommerce/global/dto/DataResponseDto.java, src/main/java/com/team9oogling/ecommerce/global/dto/MessageResponseDto.java, src/main/java/com/team9oogling/ecommerce/global/entity/Timestamped.java, src/main/java/com/team9oogling/ecommerce/global/exception/CustomException.java, src/main/java/com/team9oogling/ecommerce/global/exception/ErrorCode.java, src/main/java/com/team9oogling/ecommerce/global/exception/ExceptionResponseDto.java, src/main/java/com/team9oogling/ecommerce/global/exception/GlobalExceptionHandler.java, src/main/java/com/team9oogling/ecommerce/global/jwt/JwtPovider.java
> CU-23 초기 공통 세팅
> 1.  공통 응답 DTO 추가
> 2. Timestamped 추가
> 3. Exception 추가
> 4. gitignore 에 generated 추가
=> [2024/07/20] Feature/cu 23 add setting

.gitignore, build.gradle, src/main/java/com/team9oogling/codyus/CodyUsApplication.java, src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserLoginRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserSignupRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/entity/UserRole.java, src/main/java/com/team9oogling/codyus/domain/user/entity/UserStatus.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserRepository.java, src/main/java/com/team9oogling/codyus/domain/user/security/UserDetailsImpl.java, src/main/java/com/team9oogling/codyus/domain/user/security/UserDetailsServiceImpl.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/BcryptConfig.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/dto/DataResponseDto.java, src/main/java/com/team9oogling/codyus/global/dto/MessageResponseDto.java, src/main/java/com/team9oogling/codyus/global/dto/SecurityResponse.java, src/main/java/com/team9oogling/codyus/global/entity/Timestamped.java, src/main/java/com/team9oogling/codyus/global/exception/CustomException.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/exception/ExceptionResponseDto.java, src/main/java/com/team9oogling/codyus/global/exception/GlobalExceptionHandler.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/security/CustomAuthenticationEntryPoint.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java, src/main/java/com/team9oogling/ecommerce/global/jwt/JwtPovider.java, src/main/resources/application.properties, src/test/java/com/team9oogling/codyus/CodyUsApplicationTests.java
=> [2024/07/20] Feature/cu 3 signup login

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> CU-18
> 1. 로그아웃 기능
> 2. 로그아웃 시 토큰 블랙리스트에 추가하여 사용 금지하도록 만듦
=> [2024/07/21] feature/CU-18-create-logout

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> CU-20
> 토큰 재발급 기능 구현
> ![image](https://github.com/user-attachments/assets/2e9724b8-9e06-4707-b91d-cc5355d6f284)
=> [2024/07/21] feature/CU-20-create-token

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserWithDrawalRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserRepository.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserCleanupScheduler.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> CU-19
> 1. 회원 탈퇴 기능
> - PUT api로 ACTIVE -> INACTIVE 로 상태 변경
> - INACTIVE 상태로 30일이 경과하면 자동으로 삭제되는 기능 구현
위 캡쳐에서 inactivated_at 시간부터 30일이 경과 후 자동 삭제
=> [2024/07/21] feature/CU-19-create-withdrawal

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfilePasswordRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserWithDrawalRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserRepository.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserCleanupScheduler.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> CU-21
> 1. 프로필에서 비밀번호 수정하는 기능 구현
=> [2024/07/21] feature/CU-21-create-updatePassword

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfileAddressRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfilePasswordRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserWithDrawalRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserRepository.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserCleanupScheduler.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/JpaConfig.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> CU-22
> 1. 프로필에서 주소 수정 기능 구현
=> [2024/07/21] feature/CU-22-create-updateAddress

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfileAddressRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfilePasswordRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UpdateProfilePhoneNumberRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserWithDrawalRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserRepository.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserCleanupScheduler.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/JpaConfig.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/BlacklistedToken.java, src/main/java/com/team9oogling/codyus/global/exception/ErrorCode.java, src/main/java/com/team9oogling/codyus/global/exception/GlobalExceptionHandler.java, src/main/java/com/team9oogling/codyus/global/jwt/JwtProvider.java, src/main/java/com/team9oogling/codyus/global/repository/BlacklistedTokenRepository.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthenticationFilter.java, src/main/java/com/team9oogling/codyus/global/security/JwtAuthorizationFilter.java
> [CU-24]
> 1. 프로필에서 휴대폰 번호 수정 기능 구현
> 2. 휴대폰 번호 수정 시 아무값도 안 들어가거나, 들어간다면 11자리가 들어가도록 설
> 3. 인증 후에 유효성 검사가 이루어 지도록 예외 처리 추가 설정 
올바르게 넣었을 경우 수정 성공
아무값도 들어가지 않았거나 11자리가 아닌 경우 400 Bad Request
아무값도 들어가지 않았을 때 수정 성공
[CU-24]: https://wogys1520.atlassian.net/browse/CU-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/21] feature/CU-24-create-updatePhone

src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserSignupRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/security/UserDetailsServiceImpl.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/dto/MessageResponseDto.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/java/com/team9oogling/codyus/global/exception/CustomException.java, src/main/java/com/team9oogling/codyus/global/exception/GlobalExceptionHandler.java
> [CU-25], [CU-26]
> 1. 에러 코드 -> 상태 코드 수정 - 200번 대 추가
> 상태 코드 및 메세지 반환 Service 단에서 Controller 단으로 변경
> 인증된 사용자 Service 단에서 Controller 단으로 변경
[CU-25]: https://wogys1520.atlassian.net/browse/CU-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-26]: https://wogys1520.atlassian.net/browse/CU-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/22] feature/CU-25-CU-26-userRefactoring

src/main/java/com/team9oogling/codyus/domain/chatting/controller/ChattingRoomController.java, src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingRoomCreateResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/entity/ChattingMember.java, src/main/java/com/team9oogling/codyus/domain/chatting/entity/ChattingRoom.java, src/main/java/com/team9oogling/codyus/domain/chatting/entity/Message.java, src/main/java/com/team9oogling/codyus/domain/chatting/repository/ChattingMemberRepository.java, src/main/java/com/team9oogling/codyus/domain/chatting/repository/ChattingRoomRepository.java, src/main/java/com/team9oogling/codyus/domain/chatting/repository/MessageRepository.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/ChattingRoomService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java
> [CU-27]
> 채팅방 엔티티 생성, 
채팅방 생성 성공
채팅방 이미 존재시 오류
게시물 없을 시 오류
[CU-27]: https://wogys1520.atlassian.net/browse/CU-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/22] feature/CU-27_chattingRoomCreate

build.gradle, src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/java/com/team9oogling/codyus/domain/post/dto/PostRequestDTO.java, src/main/java/com/team9oogling/codyus/domain/post/dto/PostResponseDTO.java, src/main/java/com/team9oogling/codyus/domain/post/entity/Post.java, src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepository.java, src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepositoryCustom.java, src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/team9oogling/codyus/domain/post/service/PostService.java, src/main/java/com/team9oogling/codyus/domain/querydsl/QuerydslConfig.java
>  [CU-12]
>게시글 기능 간단하게 구현 (리팩토링 필요)
> 검색 api를 텍스트 키워드와 해시태그로 분리하였는데 한개의 API로 리팩토링 할 예정
> 
[CU-12]: https://wogys1520.atlassian.net/browse/CU-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/22] feature/CU-12 search

src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingRoomCreateResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/ChattingRoomService.java, src/main/java/com/team9oogling/codyus/domain/user/controller/UserController.java, src/main/java/com/team9oogling/codyus/global/entity/ResponseFactory.java
> [CU-29]
> 1. ResponseFactory 로 API 응답 refactoring
> 2. 빌드 안되는 곳 주석 처리
[CU-29]: https://wogys1520.atlassian.net/browse/CU-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/22] refactor/CU-29-responseRefactoring

src/main/java/com/team9oogling/codyus/domain/like/controller/LikeController.java, src/main/java/com/team9oogling/codyus/domain/like/entity/Like.java, src/main/java/com/team9oogling/codyus/domain/like/repository/LikeRepository.java, src/main/java/com/team9oogling/codyus/domain/like/service/LikeService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java
> [CU-34]
> 1. 좋아요 등록 기능 구현
> 
[CU-34]: https://wogys1520.atlassian.net/browse/CU-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/23] feature/CU-34-add-like

src/main/java/com/team9oogling/codyus/domain/like/controller/LikeController.java, src/main/java/com/team9oogling/codyus/domain/like/service/LikeService.java
> [CU-35]
> 1. 좋아요 취소 기능 구현
> 
[CU-35]: https://wogys1520.atlassian.net/browse/CU-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/24] feature/CU-35-delete-like

src/main/java/com/team9oogling/codyus/domain/chatting/controller/ChattingRoomController.java, src/main/java/com/team9oogling/codyus/domain/chatting/controller/MessageController.java, src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingMessageResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingReadRequestDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingReadResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/entity/ChattingMember.java, src/main/java/com/team9oogling/codyus/domain/chatting/entity/ChattingMemberStatus.java, src/main/java/com/team9oogling/codyus/domain/chatting/repository/ChattingMemberRepository.java, src/main/java/com/team9oogling/codyus/domain/chatting/repository/ChattingRoomRepository.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/ChattingService.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/MessageService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/java/com/team9oogling/codyus/global/exception/GlobalExceptionHandler.java
> [CU-53]
> 구독한 메세지가 user로 오면 단건 조회해서 맨위로 올리기
단건 조회 성공시 
단건 조회시 채팅방 멤버가 아닐시
채팅방 소켓 연결시 읽음 전달 받음
[CU-53]: https://wogys1520.atlassian.net/browse/CU-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/07/30] feature/CU-53_get-chat-room

src/main/java/com/team9oogling/codyus/HomeController.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/resources/static/css/header.css, src/main/resources/static/css/login.css, src/main/resources/static/css/shop.css, src/main/resources/static/css/style.css, src/main/resources/static/js/basic.js, src/main/resources/static/js/header.js, src/main/resources/static/js/login.js, src/main/resources/templates/header.html, src/main/resources/templates/index.html, src/main/resources/templates/login.html, src/main/resources/templates/shop.html
> [CU-59]
> 1. 헤더 수정
> 2. 로그인 연동
[CU-59]: https://wogys1520.atlassian.net/browse/CU-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/04] feature/CU-59-connection-login

src/main/resources/static/css/back.css, src/main/resources/static/css/header2.css, src/main/resources/static/html/back.html, src/main/resources/static/html/header2.html, src/main/resources/static/html/login.html, src/main/resources/static/html/test.html, src/main/resources/static/js/header2.js, src/main/resources/templates/find-email.html, src/main/resources/templates/find-password.html, src/main/resources/templates/main.html, src/main/resources/templates/main2.html, src/main/resources/templates/signup.html
> [CU-54], [CU-57]
> 헤더 리디자인
[CU-54]: https://wogys1520.atlassian.net/browse/CU-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-57]: https://wogys1520.atlassian.net/browse/CU-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/05] feature/CU-66-header-redesign

src/main/resources/static/css/footer2.css, src/main/resources/templates/footer2.html
> [CU-68]
> 푸터 리디자인
전체
확대
[CU-68]: https://wogys1520.atlassian.net/browse/CU-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ update - CU-68 푸터 리디자인

src/main/resources/static/css/chat.css, src/main/resources/static/js/chat.js, src/main/resources/templates/chat.html
> [CU-58]
> 
user-info,  채팅방에서 partner 이미지 클릭시 확대
rafactor -> css 색상, 크기 변경
chat.html 에 footer 추가
채팅 배경에 codyus 이미지 추가
user-info 이미지 클릭시 확대
partner 이미지 클릭시 확대
색상 변경
[CU-58]: https://wogys1520.atlassian.net/browse/CU-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/08] ✨feat: CU-58 user-info 이미지, 채팅방 파트너 이미지 추가

src/main/resources/static/js/mypage.js, src/main/resources/templates/mypage.html
> [CU-67]
> 기존 헤더 푸터 불러오는 방식이랑 달라서 코드 지웠습니다. 
[CU-67]: https://wogys1520.atlassian.net/browse/CU-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/08] Fix/CU-67-mypage-code-fix

src/main/java/com/team9oogling/codyus/domain/chatting/service/MessageService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/resources/static/css/chat.css, src/main/resources/static/js/chat.js, src/main/resources/templates/chat.html
> ex) [CU-73]
> feature/CU-73_exit-chat-room
refactor :
MessageService -> 채팅방 나가면 에러메세지 send
채팅방 나가기 클릭시 
상대방이 나갔을 경우 메세지 보낼 때
[CU-73]: https://wogys1520.atlassian.net/browse/CU-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/09] feature/CU-73_exit-chat-room

src/main/java/com/team9oogling/codyus/domain/like/controller/LikeController.java, src/main/java/com/team9oogling/codyus/domain/like/dto/LikeCountResponseDto.java, src/main/java/com/team9oogling/codyus/domain/like/repository/LikeRepository.java, src/main/java/com/team9oogling/codyus/domain/like/service/LikeService.java, src/main/java/com/team9oogling/codyus/domain/post/entity/SearchType.java, src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepositoryImpl.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/static/css/postDetail.css, src/main/resources/static/css/posts.css, src/main/resources/static/js/postDetail.js, src/main/resources/templates/postDetail.html
> ex) [CU-62], [CU-64]
> 좋아요 추가 및 취소 프론트 연동 
> 좋아요 개수 조회 및 상태 확인 추가
> 게시물 상세조회 페이지 디자인 추가 수정
좋아요 누르기 전 -> ![image](https://github.com/user-attachments/assets/bd9d96b1-5450-4646-9da1-f7b7769f414f)
좋아요 누른 후 -> ![image](https://github.com/user-attachments/assets/90cf2e50-9c2b-4195-b940-d78dfa932a86)
>
> 
[CU-62]: https://wogys1520.atlassian.net/browse/CU-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-64]: https://wogys1520.atlassian.net/browse/CU-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/09] feature - CU-64  front-postDetail, like

src/main/java/com/team9oogling/codyus/HomeController.java, src/main/java/com/team9oogling/codyus/domain/admin/controller/AdminController.java, src/main/java/com/team9oogling/codyus/domain/admin/dto/CategoryRequestDto.java, src/main/java/com/team9oogling/codyus/domain/admin/service/AdminService.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserSignupRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/User.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/application.properties, src/main/resources/static/css/signup.css, src/main/resources/static/js/admin-signup.js, src/main/resources/static/js/signup.js, src/main/resources/templates/admin-signup.html
> [CU-77], [CU-82], [CU-83]
> 1. 회원가입 페이지 수정 및 연동
> 2. 관리자 회원가입 로직 추가
> 3. 관리자 회원가입 페이지 제작 및 연동
> 4. 백오피스 카테고리 생성
1. 일반 유저 회원가입 페이지
2. 관리자 회원가입 페이지
3. 카테고리 생성
[CU-77]: https://wogys1520.atlassian.net/browse/CU-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-82]: https://wogys1520.atlassian.net/browse/CU-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-83]: https://wogys1520.atlassian.net/browse/CU-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/10] feature/CU-77-CU-82-CU-83-CREATE-SIGNUP-CATEGORY

src/main/java/com/team9oogling/codyus/domain/chatting/dto/ChattingRoomCreateResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/ChattingService.java, src/main/resources/static/js/chat.js
> [CU-88]
> ChattingRoomCreateResponseDto.java
-> 필요한 데이터 chattingRoomId 값만 반환
[CU-88]: https://wogys1520.atlassian.net/browse/CU-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/12] feature/CU-88_front-chat-create

src/main/resources/static/css/postDetail.css, src/main/resources/static/js/postDetail.js, src/main/resources/templates/postDetail.html
> ex) [CU-64]
> 게시물 상세조회에 채팅하기 기능 연동 
[CU-64]: https://wogys1520.atlassian.net/browse/CU-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/12] 🎉update - CU-64 채팅방 생성하기 연동

src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/java/com/team9oogling/codyus/domain/post/dto/PostRequestDto.java, src/main/java/com/team9oogling/codyus/domain/post/entity/Post.java, src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepository.java, src/main/java/com/team9oogling/codyus/domain/post/service/PostService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/static/js/postCreate.js
> [CU-89]
> 1. 카테고리 리스트로 받아와서 분리
> 2. 카테고리별 게시글 조회
[CU-89]: https://wogys1520.atlassian.net/browse/CU-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/12] feature/CU-89-create-get-postsByCategory

src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/resources/static/css/likePage.css, src/main/resources/static/js/likePage.js, src/main/resources/templates/likePage.html
> ex) [CU-92]
> 내가 좋아요 누른 게시물을 조회하는 관심 페이지 구현
> 관심페이지에서 하트를 누를시 삭제됨
[CU-92]: https://wogys1520.atlassian.net/browse/CU-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/13] feature/ CU-92 front-like-mypage 

src/main/java/com/team9oogling/codyus/domain/like/service/LikeService.java
> [CU-34], [CU-35]
> 좋아요 관련 오류 발생으로 (좋아요를 누르지 않았는데 이미 좋아요를 누른 게시물이라고 하는 상태) 코드 수정
[CU-34]: https://wogys1520.atlassian.net/browse/CU-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CU-35]: https://wogys1520.atlassian.net/browse/CU-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/13] fix/ CU-87 likeservice-code

src/main/java/com/team9oogling/codyus/domain/user/controller/UserQuestionController.java, src/main/java/com/team9oogling/codyus/domain/user/dto/UserQuestionRequestDto.java, src/main/java/com/team9oogling/codyus/domain/user/entity/UserQuestion.java, src/main/java/com/team9oogling/codyus/domain/user/repository/UserQuestionRepository.java, src/main/java/com/team9oogling/codyus/domain/user/service/UserQuestionService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/static/css/contact-us.css, src/main/resources/static/js/contact-us.js, src/main/resources/templates/contact-us.html
> ex) [CU-93]
> 고객센터 QnA 생성 기능 추가 
아무것도 입력하지 않았거나 이름 이메일 문의내용중 하나라도 입력하지 않았을 때
문의내용 500자 이상일때
500자 이상 되면 자동으로 자르고 등록했을 경우
데이터베이스
[CU-93]: https://wogys1520.atlassian.net/browse/CU-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/14] feature/CU-93-user-question

src/main/resources/static/css/header.css, src/main/resources/static/js/header.js, src/main/resources/static/js/myPage.js, src/main/resources/templates/myPage.html, src/main/resources/templates/shop.html
> ex) [CU-94]
> header home style shop 기본 굵기 600 -> 400으로 변경
페이지 이동시 굵기 800 으로 변경
mypage에서 게시물 더보기 클릭시 posts로 이동
shop 헤더 추가
토큰없이 마이페이지 접속시 login페이지 이동
[CU-94]: https://wogys1520.atlassian.net/browse/CU-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/14] feature/CU-94-front-refactor

src/main/java/com/team9oogling/codyus/domain/like/controller/LikeController.java, src/main/java/com/team9oogling/codyus/domain/like/repository/LikeRepository.java, src/main/java/com/team9oogling/codyus/domain/like/service/LikeService.java, src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/java/com/team9oogling/codyus/domain/post/service/PostService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/static/css/likePage.css, src/main/resources/static/css/posts.css, src/main/resources/static/js/category.js, src/main/resources/static/js/likePage.js, src/main/resources/static/js/posts.js, src/main/resources/templates/category-page.html, src/main/resources/templates/header.html, src/main/resources/templates/likePage.html
> ex) [CU-92]
>스타일에 제목 대신 닉네임, 하트 대신 likes
> 관심 페이지 페이지네이션 추가
> 카테고리는 구현하지 못했습니다
=> [2024/08/14] feature/CU-92 front-posts-refactoring

src/main/resources/static/css/chat.css, src/main/resources/static/css/footer.css, src/main/resources/static/css/header.css, src/main/resources/static/css/myPage.css, src/main/resources/static/js/myPage.js, src/main/resources/templates/chat.html, src/main/resources/templates/myPage.html
> [CU-101]
> 1. 헤더 수정
> 2. 마이페이지 수정 - 오버레이 헤더랑 클래스 분리
[CU-101]: https://wogys1520.atlassian.net/browse/CU-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/14] fix/CU-101-fix-header-mypage

src/main/java/com/team9oogling/codyus/global/runner/dummyDataRunner.java, src/main/resources/static/css/chat.css, src/main/resources/static/js/chat.js
> ex) [CU-96]
> runner 이용 더미데이터 생성 
refactor -> 채팅 배경 codyus 크기 작게 조정
채팅방 나가기 검은색모양에서 배경색 없애고 나가기만 검정색 변경 더보기 각지게 변경
상수 값만 바꾸면 더 넣을 수 있습니다.   user 10개 postcount 100개면 10*100 곱으로 됩니다. 
[CU-96]: https://wogys1520.atlassian.net/browse/CU-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/14] feature/CU-96-add-dummy-data

src/main/resources/static/css/shop.css, src/main/resources/static/js/shop.js, src/main/resources/templates/shop.html
> ex) [CU-103]
> shop 프론트 작업
각각 페이징 처리 
사진 마우스 호버 1.05배 확대 커서 
tite 넘어가면 hidden 처리
[CU-103]: https://wogys1520.atlassian.net/browse/CU-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/16] feature/CU-103-shop-front

src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/resources/static/js/myPage.js, src/main/resources/templates/myPage.html
> ex) [CU-62] 
> 마이페이지에서 관심 리스트 및 페이지네이션 추가
> 관심 (더보기)누르면 관심 페이지로 이동 
[CU-62]: https://wogys1520.atlassian.net/browse/CU-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/16] feature/CU-62 front-mypage-like_list

src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/resources/static/css/index.css, src/main/resources/static/css/man.css, src/main/resources/static/css/myPage.css, src/main/resources/static/css/shop.css, src/main/resources/static/js/myPage.js, src/main/resources/templates/myPage.html
=> ♻️refactor: CSS 나노미터 이동

src/main/resources/static/css/myPage.css, src/main/resources/static/js/myPage.js
> [CU-98]
> 1. 개인정보 부분 오류 수정
> 2. 디자인 아주 미세하게 조정
[CU-98]: https://wogys1520.atlassian.net/browse/CU-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/16] fix/CU-98-fix-front

src/main/resources/static/js/contact-us.js
> [CU-104]
> 1. contact-us 수정
[CU-104]: https://wogys1520.atlassian.net/browse/CU-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ update - CU-104 토큰 저장 방식 수정

src/main/java/com/team9oogling/codyus/domain/like/controller/LikeController.java, src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/resources/static/css/chat.css
> 채팅방 안에 게시물 길어진거 히든처리
system.out.print 제거
=> ♻️refactor: css리펙토링 System.out.print 제거

src/main/resources/static/css/searchResult.css, src/main/resources/static/js/basic.js, src/main/resources/static/js/likePage.js, src/main/resources/static/js/login.js, src/main/resources/static/js/myPage.js, src/main/resources/static/js/postCreate.js, src/main/resources/static/js/searchResult.js, src/main/resources/templates/searchResult.html
> [CU-105]
> 1. 배포 전 통합
[CU-105]: https://wogys1520.atlassian.net/browse/CU-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/16] feature/CU-105-deploy

src/main/resources/static/js/postDetail.js
> 비로그인시 디테일 하트 추가
로그인x 시 하트 추가
=> [2024/08/16]♻️refactor: detail 하트

src/main/java/com/team9oogling/codyus/global/config/webSocketConfig.java
> setAllowedOrigins -> 허용 로컬호스트랑 https://codyus.shop
=> ♻️refactor: 웹소켓 config setAllowedOrigins -> 허용 로컬호스트랑 https://codyus.shop

src/main/resources/templates/footer.html, src/main/resources/templates/posts.html
> [CU-105]
> 1. 푸터 수정
> 2. 스타일 페이지 수정
[CU-105]: https://wogys1520.atlassian.net/browse/CU-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/16] Fix/cu 105 deploy

src/main/java/com/team9oogling/codyus/global/config/webSocketConfig.java
> config setAllowedOrigins -> "*" 모두허용
=> ♻️refactor: 웹소켓 config setAllowedOrigins -> "*" 모두허용

src/main/resources/static/css/chat.css
=> [2024/08/17]♻️refactor: 채팅 css

src/main/java/com/team9oogling/codyus/HomeController.java, src/main/java/com/team9oogling/codyus/domain/oauth/controller/OAuthController.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/resources/application.properties, src/main/resources/static/css/index.css, src/main/resources/static/css/postDetail.css, src/main/resources/static/css/searchResult.css, src/main/resources/static/css/shop.css, src/main/resources/static/css/unisex.css, src/main/resources/static/js/chat.js, src/main/resources/static/js/likePage.js, src/main/resources/static/js/postDetail.js, src/main/resources/static/js/posts.js, src/main/resources/static/js/searchResult.js, src/main/resources/static/js/shop.js, src/main/resources/static/js/unisex.js, src/main/resources/templates/header.html, src/main/resources/templates/index.html, src/main/resources/templates/login.html, src/main/resources/templates/postDetail.html, src/main/resources/templates/searchResult.html, src/main/resources/templates/unisex.html
> [CU-105]
[CU-105]: https://wogys1520.atlassian.net/browse/CU-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/18] Fix/cu 105 deploy

src/main/resources/static/js/chat.js
=> [2024/08/18]♻️refactor: chat.js refactor

src/main/resources/static/js/postCreate.js
> [CU-106]
> 파일 업로드 시 파일 용량 제한 추가 (PostCreate.js)
[CU-106]: https://wogys1520.atlassian.net/browse/CU-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/18] feat/CU-106-File-size-limit

src/main/java/com/team9oogling/codyus/domain/chatting/controller/ChattingRoomController.java, src/main/java/com/team9oogling/codyus/domain/chatting/dto/UnReadChattingCountResponseDto.java, src/main/java/com/team9oogling/codyus/domain/chatting/service/ChattingService.java, src/main/java/com/team9oogling/codyus/global/entity/StatusCode.java, src/main/resources/static/css/header.css, src/main/resources/static/js/header.js, src/main/resources/static/js/postCreate.js, src/main/resources/static/js/shop.js, src/main/resources/templates/header.html
> ex) [CU-107]
> 채팅 알림 안읽음 갯수 polling 방식 구현 -> 10초마다 fetch 불러 옵니다.
shop 에서 하트누르면 page 안뜨는거 post-data-id 값넣어서 post 페이지로 이동하게 만듬
채팅 알림 갯수 
[CU-107]: https://wogys1520.atlassian.net/browse/CU-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/19] ✨feat/CU-107-chat-alram-poling

src/main/resources/static/js/chat.js, src/main/resources/static/js/header.js, src/main/resources/templates/header.html
> ex) [CU-107]
> 채팅 알림 소켓 방식으로 바꿈
[CU-107]: https://wogys1520.atlassian.net/browse/CU-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/19] ✨feat: CU-107 채팅 알림 소켓 연결

src/main/resources/static/css/chat.css, src/main/resources/static/js/chat.js
넘어가는거 밑으로 처리
가격 없애고 text right 끝
=> [2024/08/20] refactor: chat.css 

src/main/resources/static/css/postCreate.css, src/main/resources/static/js/postCreate.js, src/main/resources/templates/postCreate.html
> ex) [CU-63]
> 제목(50자 이내), 내용(300자 이내), 해시태그(20개 이내) 글자 수 제한 -> 제한 이상 적을때 생성 버튼 누를시 알림이 뜸
[CU-63]: https://wogys1520.atlassian.net/browse/CU-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/21] ✨update - CU-63 제목,내용, 해시태그 글자수 제한

src/main/resources/static/css/postDetail.css, src/main/resources/static/css/posts.css
> post.css , postDetails.css
글자수 넘어가는 거 줄처리
스타일 
디테일
=> [2024/08/21] refactor : post.css ,postDetail.css

src/main/java/com/team9oogling/codyus/domain/post/repository/PostRepositoryImpl.java, src/main/resources/static/css/postDetail.css, src/main/resources/static/js/postCreate.js, src/main/resources/static/js/posts.js, src/main/resources/static/js/searchResult.js, src/main/resources/static/js/shop.js
> [CU-105]
> 1. 최종 배포
[CU-105]: https://wogys1520.atlassian.net/browse/CU-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/08/21] Fix/CU-105-last-deploy

src/main/java/com/team9oogling/codyus/domain/post/dto/PostResponseDto.java, src/main/resources/static/js/man.js, src/main/resources/static/js/postDetail.js, src/main/resources/static/js/posts.js, src/main/resources/static/js/ranking.js, src/main/resources/static/js/shop.js, src/main/resources/static/js/unisex.js, src/main/resources/static/js/woman.js
> ex) [CU-108]
> Likes  post 불러 올때 count로 조회로 변경
[CU-108]: https://wogys1520.atlassian.net/browse/CU-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix : CU-108 '라이크 카운트 메서드 제거, 게시물과 함께 가져오도록 변경'

src/main/java/com/team9oogling/codyus/HomeController.java, src/main/java/com/team9oogling/codyus/domain/post/controller/PostController.java, src/main/java/com/team9oogling/codyus/domain/post/service/PostService.java, src/main/java/com/team9oogling/codyus/global/config/SecurityConfig.java, src/main/resources/static/css/postDetail.css, src/main/resources/static/css/postUpdate.css, src/main/resources/static/js/postDetail.js, src/main/resources/static/js/postUpdate.js, src/main/resources/templates/postDetail.html, src/main/resources/templates/postUpdate.html
> ex) [CU-109]
> 수정 페이지 추가
[CU-109]: https://wogys1520.atlassian.net/browse/CU-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2024/09/03] feature/CU-109 수정 페이지 추가

.github/workflows/deploy.yml
=> ssh 디버그 모드 활성화

.github/workflows/deploy.yml
ubuntu ssh 권한 재설정
> ex) #이슈번호, #이슈번호
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> ubuntu ssh 권한 재설정

.github/workflows/deploy.yml
직접 run으로 수정
> ex) #이슈번호, #이슈번호
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 직접 run으로 수정

.github/workflows/deploy.yml
private key 줄바꿈 수정
> ex) #이슈번호, #이슈번호
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> private key 줄바꿈 수정

.github/workflows/deploy.yml
ssh master 버전으로 수정
> ex) #이슈번호, #이슈번호
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> ssh master 버전으로 수정

.github/workflows/deploy.yml
=> 환경변수 설정값 전달 추가
